### ISSUE TITLE
请教爬虫的proxy相关

### ISSUE THREAD

**Issue by LuckyFork** [junweizeng/movie_recommendation_system_server#3]
大佬您好，我目前有免费的oss仓库，但是发现代理不可用，请问您当时购买的是什么量级的proxy可以给个参考吗？谢谢！！

**Comment by junweizeng** [comment]
A dup of https://github.com/junweizeng/douban_movie_spider_mrs/issues/2.

该项目爬虫相关问题请转向爬虫项目[douban_movie_spider_mrs/issues](https://github.com/junweizeng/douban_movie_spider_mrs/issues)提问，这里关闭该issue。
